import type { Task } from './types';

// Mock data matching the HTML prototype.
// Each item is tagged with its source so you can see which integration
// it would come from once the real APIs are wired up.

export const mockTasks: Task[] = [
  {
    id: 1,
    title: 'Send revised proposal to Meridian Health',
    desc: "Jamie asked for updated pricing on Tier 2 after Friday's call. Contract window closes this week.",
    priority: 'high',
    activity: 'email',
    client: 'Meridian Health',
    project: 'Q1 Proposal',
    source: 'Granola · Friday 2pm',
    dueDate: '2026-03-05',
    completed: false,
    manual: false,
  },
  {
    id: 2,
    title: 'Follow up: Apex Foundation grant timeline',
    desc: 'No response to last two emails. Board meeting is March 15 — need sign-off before then.',
    priority: 'high',
    activity: 'email',
    client: 'Apex Foundation',
    project: 'Grant Renewal',
    source: 'Superhuman · 2 days ago',
    dueDate: '2026-03-15',
    completed: false,
    manual: false,
  },
  {
    id: 3,
    title: 'Review SOW draft for Westside Creative',
    desc: 'Tom sent over v2 of the scope — two open questions on deliverables timeline.',
    priority: 'high',
    activity: 'focus',
    client: 'Westside Creative',
    project: 'New SOW',
    source: 'Superhuman · Today 9am',
    dueDate: '2026-03-04',
    completed: false,
    manual: false,
  },
  {
    id: 4,
    title: 'Prep for Meridian Health check-in call',
    desc: '30-min call Thursday 2pm. Key goal: confirm deal timeline and next steps.',
    priority: 'medium',
    activity: 'meeting',
    client: 'Meridian Health',
    project: 'Q1 Proposal',
    source: 'Granola · Calendar sync',
    dueDate: '2026-03-05',
    completed: false,
    manual: false,
  },
  {
    id: 5,
    title: 'Update HubSpot deal stage: Apex Foundation',
    desc: "Deal has been in 'Proposal' for 3 weeks. Either advance or flag as at-risk.",
    priority: 'medium',
    activity: 'other',
    client: 'Apex Foundation',
    project: 'Grant Renewal',
    source: 'HubSpot · Stale deal',
    dueDate: null,
    completed: false,
    manual: false,
  },
  {
    id: 6,
    title: 'Block 2hrs to finalize Q1 impact report',
    desc: 'Deadline is end of week. First draft 70% done — needs data section and exec summary.',
    priority: 'medium',
    activity: 'focus',
    client: 'Internal',
    project: 'Q1 Impact Report',
    source: 'Manual',
    dueDate: '2026-03-06',
    completed: false,
    manual: true,
  },
  {
    id: 7,
    title: 'Reply to Carlos re: referral intro',
    desc: 'Carlos connected you with a potential new client. Short reply to confirm interest.',
    priority: 'low',
    activity: 'email',
    client: 'Prospects',
    project: 'Business Dev',
    source: 'Superhuman · Yesterday',
    dueDate: '2026-03-03',
    completed: false,
    manual: false,
  },
  {
    id: 8,
    title: 'Schedule quarterly review — Westside Creative',
    desc: 'QBR overdue by 2 weeks. 60-min slot needed in March.',
    priority: 'low',
    activity: 'meeting',
    client: 'Westside Creative',
    project: 'Account Health',
    source: 'Granola · Meeting notes',
    dueDate: '2026-03-02',
    completed: true,
    manual: false,
  },
];

export const defaultStrategy = [
  'Close Meridian Health deal by Friday',
  'Unblock Apex Foundation grant renewal',
  'Clear backlog on Westside Creative before new SOW',
];
